name: CI
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['8.1', '8.2', '8.3']
                laravel: ['10.*', '11.*', '12.*']
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, curl, json, dom
                  tools: composer:v2
            - name: Configure Laravel version
              run: |
                  composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
            - run: composer install --no-interaction --prefer-dist
            - run: composer test
